version: '3.2'
services:
  kim_hwang_batch_db:
    container_name: kim_hwang_batch_db
    image: mariadb:10.4
    restart: always
    ports:
      - "33306:3306"
    volumes:
      - ~/docker_repo/kim_hwang_batch_db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=spring_batch
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    command: mysqld --character-set-server=utf8mb4 --init-file /data/application/init.sql